#include "lxgui/gui_uiobject.hpp"
#include "lxgui/gui_frame.hpp"
#include "lxgui/gui_focusframe.hpp"
#include "lxgui/gui_layeredregion.hpp"
#include "lxgui/gui_button.hpp"
#include "lxgui/gui_checkbutton.hpp"
#include "lxgui/gui_editbox.hpp"
#include "lxgui/gui_scrollframe.hpp"
#include "lxgui/gui_slider.hpp"
#include "lxgui/gui_statusbar.hpp"
#include "lxgui/gui_fontstring.hpp"
#include "lxgui/gui_texture.hpp"

/****************/
/* Methods list */
/****************/

/* [#] Here we register every member function of each class. As Lunar doesn't
*  know about inheritance, you're obliged to register every member function of a
*  C++ class, including the ones inherited. Else you won't be able to call them
*  in LUA.
*/

#define method(widget, function) {#function, &lua_##widget::_##function}

namespace lxgui {
namespace gui
{
    const char lua_virtual_glue::className[] = "VirtualGlue";
    const char* lua_virtual_glue::classList[] = {"VirtualGlue", 0};
    lua::Lunar<lua_virtual_glue>::RegType lua_virtual_glue::methods[] = {
        {"dt", &lua_virtual_glue::get_data_table},

        // VirtualGlue
        method(virtual_glue, mark_for_copy),
        method(virtual_glue, get_base),
        method(virtual_glue, get_name),

        {0,0}
    };

    const char lua_uiobject::className[] = "UIObject";
    const char* lua_uiobject::classList[] = {"UIObject",
        "Frame", "FocusFrame", "Button", "CheckButton", "EditBox", "ScrollFrame",
        "Slider", "StatusBar", "LayeredRegion", "Texture", "FontString", 0
    };
    lua::Lunar<lua_uiobject>::RegType lua_uiobject::methods[] = {
        {"dt", &lua_uiobject::get_data_table},

        // uiobject
        method(uiobject, get_alpha),
        method(uiobject, get_name),
        method(uiobject, get_object_type),
        method(uiobject, is_object_type),
        method(uiobject, set_alpha),

        method(uiobject, clear_all_points),
        method(uiobject, get_base),
        method(uiobject, get_bottom),
        method(uiobject, get_center),
        method(uiobject, get_height),
        method(uiobject, get_left),
        method(uiobject, get_num_point),
        method(uiobject, get_parent),
        method(uiobject, get_point),
        method(uiobject, get_right),
        method(uiobject, get_top),
        method(uiobject, get_width),
        method(uiobject, hide),
        method(uiobject, is_shown),
        method(uiobject, is_visible),
        method(uiobject, set_all_points),
        method(uiobject, set_height),
        method(uiobject, set_parent),
        method(uiobject, set_point),
        method(uiobject, set_rel_point),
        method(uiobject, set_width),
        method(uiobject, show),
        {0,0}
    };

    const char  lua_frame::className[] = "Frame";
    const char* lua_frame::classList[] = {"Frame",
        "FocusFrame", "Button", "CheckButton", "EditBox", "ScrollFrame",
        "Slider", "StatusBar", 0
    };
    lua::Lunar<lua_frame>::RegType lua_frame::methods[] = {
        {"dt", &lua_frame::get_data_table},

        // uiobject (inherited)
        method(frame, get_alpha),
        method(frame, get_name),
        method(frame, get_object_type),
        method(frame, is_object_type),
        method(frame, set_alpha),

        method(frame, clear_all_points),
        method(frame, get_base),
        method(frame, get_bottom),
        method(frame, get_center),
        method(frame, get_height),
        method(frame, get_left),
        method(frame, get_num_point),
        method(frame, get_parent),
        method(frame, get_point),
        method(frame, get_right),
        method(frame, get_top),
        method(frame, get_width),
        method(frame, hide),
        method(frame, is_shown),
        method(frame, is_visible),
        method(frame, set_all_points),
        method(frame, set_height),
        method(frame, set_parent),
        method(frame, set_point),
        method(frame, set_rel_point),
        method(frame, set_width),
        method(frame, show),

        // frame
        method(frame, create_font_string),
        method(frame, create_texture),
        method(frame, create_title_region),
        method(frame, disable_draw_layer),
        method(frame, enable_draw_layer),
        method(frame, enable_keyboard),
        method(frame, enable_mouse),
        method(frame, enable_mouse_wheel),
        method(frame, get_backdrop),
        method(frame, get_backdrop_border_color),
        method(frame, get_backdrop_color),
        method(frame, get_children),
        method(frame, get_effective_alpha),
        method(frame, get_effective_scale),
        method(frame, get_frame_level),
        method(frame, get_frame_strata),
        method(frame, get_frame_type),
        method(frame, get_hit_rect_insets),
        method(frame, get_id),
        method(frame, get_max_resize),
        method(frame, get_min_resize),
        method(frame, set_max_width),
        method(frame, set_max_height),
        method(frame, set_min_width),
        method(frame, set_min_height),
        method(frame, get_num_children),
        method(frame, get_num_regions),
        method(frame, get_scale),
        method(frame, get_script),
        method(frame, get_title_region),
        method(frame, has_script),
        method(frame, is_clamped_to_screen),
        method(frame, is_frame_type),
        method(frame, is_keyboard_enabled),
        method(frame, is_mouse_enabled),
        method(frame, is_mouse_wheel_enabled),
        method(frame, is_movable),
        method(frame, is_resizable),
        method(frame, is_top_level),
        method(frame, is_user_placed),
        method(frame, on),
        method(frame, raise),
        method(frame, register_all_events),
        method(frame, register_event),
        method(frame, register_for_drag),
        method(frame, set_backdrop),
        method(frame, set_backdrop_border_color),
        method(frame, set_backdrop_color),
        method(frame, set_clamped_to_screen),
        method(frame, set_frame_strata),
        method(frame, set_hit_rect_insets),
        method(frame, set_max_resize),
        method(frame, set_min_resize),
        method(frame, set_movable),
        method(frame, set_resizable),
        method(frame, set_scale),
        method(frame, set_script),
        method(frame, set_top_level),
        method(frame, set_user_placed),
        method(frame, start_moving),
        method(frame, start_sizing),
        method(frame, stop_moving_or_sizing),
        method(frame, unregister_all_events),
        method(frame, unregister_event),

        {0,0}
    };

    const char  lua_check_button::className[] = "CheckButton";
    const char* lua_check_button::classList[] = {"CheckButton", 0};
    lua::Lunar<lua_check_button>::RegType lua_check_button::methods[] = {
        {"dt", &lua_check_button::get_data_table},

        // uiobject (inherited)
        method(check_button, get_alpha),
        method(check_button, get_name),
        method(check_button, get_object_type),
        method(check_button, is_object_type),
        method(check_button, set_alpha),

        method(check_button, clear_all_points),
        method(check_button, get_base),
        method(check_button, get_bottom),
        method(check_button, get_center),
        method(check_button, get_height),
        method(check_button, get_left),
        method(check_button, get_num_point),
        method(check_button, get_parent),
        method(check_button, get_point),
        method(check_button, get_right),
        method(check_button, get_top),
        method(check_button, get_width),
        method(check_button, hide),
        method(check_button, is_shown),
        method(check_button, is_visible),
        method(check_button, set_all_points),
        method(check_button, set_height),
        method(check_button, set_parent),
        method(check_button, set_point),
        method(check_button, set_rel_point),
        method(check_button, set_width),
        method(check_button, show),

        // frame (inherited)
        method(check_button, create_font_string),
        method(check_button, create_texture),
        method(check_button, create_title_region),
        method(check_button, disable_draw_layer),
        method(check_button, enable_draw_layer),
        method(check_button, enable_keyboard),
        method(check_button, enable_mouse),
        method(check_button, enable_mouse_wheel),
        method(check_button, get_backdrop),
        method(check_button, get_backdrop_border_color),
        method(check_button, get_backdrop_color),
        method(check_button, get_children),
        method(check_button, get_effective_alpha),
        method(check_button, get_effective_scale),
        method(check_button, get_frame_level),
        method(check_button, get_frame_strata),
        method(check_button, get_frame_type),
        method(check_button, get_hit_rect_insets),
        method(check_button, get_id),
        method(check_button, get_max_resize),
        method(check_button, get_min_resize),
        method(check_button, set_max_width),
        method(check_button, set_max_height),
        method(check_button, set_min_width),
        method(check_button, set_min_height),
        method(check_button, get_num_children),
        method(check_button, get_num_regions),
        method(check_button, get_scale),
        method(check_button, get_script),
        method(check_button, get_title_region),
        method(check_button, has_script),
        method(check_button, is_clamped_to_screen),
        method(check_button, is_frame_type),
        method(check_button, is_keyboard_enabled),
        method(check_button, is_mouse_enabled),
        method(check_button, is_mouse_wheel_enabled),
        method(check_button, is_movable),
        method(check_button, is_resizable),
        method(check_button, is_top_level),
        method(check_button, is_user_placed),
        method(check_button, on),
        method(check_button, raise),
        method(check_button, register_all_events),
        method(check_button, register_event),
        method(check_button, register_for_drag),
        method(check_button, set_backdrop),
        method(check_button, set_backdrop_border_color),
        method(check_button, set_backdrop_color),
        method(check_button, set_clamped_to_screen),
        method(check_button, set_frame_strata),
        method(check_button, set_hit_rect_insets),
        method(check_button, set_max_resize),
        method(check_button, set_min_resize),
        method(check_button, set_movable),
        method(check_button, set_resizable),
        method(check_button, set_scale),
        method(check_button, set_script),
        method(check_button, set_top_level),
        method(check_button, set_user_placed),
        method(check_button, start_moving),
        method(check_button, start_sizing),
        method(check_button, stop_moving_or_sizing),
        method(check_button, unregister_all_events),
        method(check_button, unregister_event),

        // Button (inherited)
        method(check_button, click),
        method(check_button, disable),
        method(check_button, enable),
        method(check_button, get_button_state),
        method(check_button, get_disabled_font_object),
        method(check_button, get_disabled_text_color),
        method(check_button, get_disabled_texture),
        method(check_button, get_highlight_font_object),
        method(check_button, get_highlight_text_color),
        method(check_button, get_highlight_texture),
        method(check_button, get_normal_font_object),
        method(check_button, get_normal_texture),
        method(check_button, get_pushed_text_offset),
        method(check_button, get_pushed_texture),
        method(check_button, get_text),
        method(check_button, get_text_height),
        method(check_button, get_text_width),
        method(check_button, is_enabled),
        method(check_button, lock_highlight),
        method(check_button, set_button_state),
        method(check_button, set_disabled_font_object),
        method(check_button, set_disabled_text_color),
        method(check_button, set_disabled_texture),
        method(check_button, set_highlight_font_object),
        method(check_button, set_highlight_text_color),
        method(check_button, set_highlight_texture),
        method(check_button, set_normal_font_object),
        method(check_button, set_normal_text_color),
        method(check_button, set_normal_texture),
        method(check_button, set_pushed_text_offset),
        method(check_button, set_pushed_texture),
        method(check_button, set_text),
        method(check_button, unlock_highlight),

        // CheckButton
        method(check_button, is_checked),
        method(check_button, get_checked_texture),
        method(check_button, get_disabled_checked_texture),
        method(check_button, set_checked),
        method(check_button, set_checked_texture),
        method(check_button, set_disabled_checked_texture),

        {0,0}
    };

    const char  lua_status_bar::className[] = "StatusBar";
    const char* lua_status_bar::classList[] = {"StatusBar", 0};
    lua::Lunar<lua_status_bar>::RegType lua_status_bar::methods[] = {
        {"dt", &lua_status_bar::get_data_table},

        // uiobject (inherited)
        method(status_bar, get_alpha),
        method(status_bar, get_name),
        method(status_bar, get_object_type),
        method(status_bar, is_object_type),
        method(status_bar, set_alpha),

        method(status_bar, clear_all_points),
        method(status_bar, get_base),
        method(status_bar, get_bottom),
        method(status_bar, get_center),
        method(status_bar, get_height),
        method(status_bar, get_left),
        method(status_bar, get_num_point),
        method(status_bar, get_parent),
        method(status_bar, get_point),
        method(status_bar, get_right),
        method(status_bar, get_top),
        method(status_bar, get_width),
        method(status_bar, hide),
        method(status_bar, is_shown),
        method(status_bar, is_visible),
        method(status_bar, set_all_points),
        method(status_bar, set_height),
        method(status_bar, set_parent),
        method(status_bar, set_point),
        method(status_bar, set_rel_point),
        method(status_bar, set_width),
        method(status_bar, show),

        // frame (inherited)
        method(status_bar, create_font_string),
        method(status_bar, create_texture),
        method(status_bar, create_title_region),
        method(status_bar, disable_draw_layer),
        method(status_bar, enable_draw_layer),
        method(status_bar, enable_keyboard),
        method(status_bar, enable_mouse),
        method(status_bar, enable_mouse_wheel),
        method(status_bar, get_backdrop),
        method(status_bar, get_backdrop_border_color),
        method(status_bar, get_backdrop_color),
        method(status_bar, get_children),
        method(status_bar, get_effective_alpha),
        method(status_bar, get_effective_scale),
        method(status_bar, get_frame_level),
        method(status_bar, get_frame_strata),
        method(status_bar, get_frame_type),
        method(status_bar, get_hit_rect_insets),
        method(status_bar, get_id),
        method(status_bar, get_max_resize),
        method(status_bar, get_min_resize),
        method(status_bar, set_max_width),
        method(status_bar, set_max_height),
        method(status_bar, set_min_width),
        method(status_bar, set_min_height),
        method(status_bar, get_num_children),
        method(status_bar, get_num_regions),
        method(status_bar, get_scale),
        method(status_bar, get_script),
        method(status_bar, get_title_region),
        method(status_bar, has_script),
        method(status_bar, is_clamped_to_screen),
        method(status_bar, is_frame_type),
        method(status_bar, is_keyboard_enabled),
        method(status_bar, is_mouse_enabled),
        method(status_bar, is_mouse_wheel_enabled),
        method(status_bar, is_movable),
        method(status_bar, is_resizable),
        method(status_bar, is_top_level),
        method(status_bar, is_user_placed),
        method(status_bar, on),
        method(status_bar, raise),
        method(status_bar, register_all_events),
        method(status_bar, register_event),
        method(status_bar, register_for_drag),
        method(status_bar, set_backdrop),
        method(status_bar, set_backdrop_border_color),
        method(status_bar, set_backdrop_color),
        method(status_bar, set_clamped_to_screen),
        method(status_bar, set_frame_strata),
        method(status_bar, set_hit_rect_insets),
        method(status_bar, set_max_resize),
        method(status_bar, set_min_resize),
        method(status_bar, set_movable),
        method(status_bar, set_resizable),
        method(status_bar, set_scale),
        method(status_bar, set_script),
        method(status_bar, set_top_level),
        method(status_bar, set_user_placed),
        method(status_bar, start_moving),
        method(status_bar, start_sizing),
        method(status_bar, stop_moving_or_sizing),
        method(status_bar, unregister_all_events),
        method(status_bar, unregister_event),

        // StatusBar
        method(status_bar, get_min_max_values),
        method(status_bar, get_orientation),
        method(status_bar, is_reversed),
        method(status_bar, get_status_bar_color),
        method(status_bar, get_status_bar_texture),
        method(status_bar, get_value),
        method(status_bar, set_min_max_values),
        method(status_bar, set_orientation),
        method(status_bar, set_reversed),
        method(status_bar, set_status_bar_color),
        method(status_bar, set_status_bar_texture),
        method(status_bar, set_value),

        {0,0}
    };

    const char  lua_focus_frame::className[] = "FocusFrame";
    const char* lua_focus_frame::classList[] = {"FocusFrame", "EditBox", 0};
    lua::Lunar<lua_focus_frame>::RegType lua_focus_frame::methods[] = {
        {"dt", &lua_focus_frame::get_data_table},

        // uiobject (inherited)
        method(focus_frame, get_alpha),
        method(focus_frame, get_name),
        method(focus_frame, get_object_type),
        method(focus_frame, is_object_type),
        method(focus_frame, set_alpha),

        method(focus_frame, clear_all_points),
        method(focus_frame, get_base),
        method(focus_frame, get_bottom),
        method(focus_frame, get_center),
        method(focus_frame, get_height),
        method(focus_frame, get_left),
        method(focus_frame, get_num_point),
        method(focus_frame, get_parent),
        method(focus_frame, get_point),
        method(focus_frame, get_right),
        method(focus_frame, get_top),
        method(focus_frame, get_width),
        method(focus_frame, hide),
        method(focus_frame, is_shown),
        method(focus_frame, is_visible),
        method(focus_frame, set_all_points),
        method(focus_frame, set_height),
        method(focus_frame, set_parent),
        method(focus_frame, set_point),
        method(focus_frame, set_rel_point),
        method(focus_frame, set_width),
        method(focus_frame, show),

        // frame (inherited)
        method(focus_frame, create_font_string),
        method(focus_frame, create_texture),
        method(focus_frame, create_title_region),
        method(focus_frame, disable_draw_layer),
        method(focus_frame, enable_draw_layer),
        method(focus_frame, enable_keyboard),
        method(focus_frame, enable_mouse),
        method(focus_frame, enable_mouse_wheel),
        method(focus_frame, get_backdrop),
        method(focus_frame, get_backdrop_border_color),
        method(focus_frame, get_backdrop_color),
        method(focus_frame, get_children),
        method(focus_frame, get_effective_alpha),
        method(focus_frame, get_effective_scale),
        method(focus_frame, get_frame_level),
        method(focus_frame, get_frame_strata),
        method(focus_frame, get_frame_type),
        method(focus_frame, get_hit_rect_insets),
        method(focus_frame, get_id),
        method(focus_frame, get_max_resize),
        method(focus_frame, get_min_resize),
        method(focus_frame, set_max_width),
        method(focus_frame, set_max_height),
        method(focus_frame, set_min_width),
        method(focus_frame, set_min_height),
        method(focus_frame, get_num_children),
        method(focus_frame, get_num_regions),
        method(focus_frame, get_scale),
        method(focus_frame, get_script),
        method(focus_frame, get_title_region),
        method(focus_frame, has_script),
        method(focus_frame, is_clamped_to_screen),
        method(focus_frame, is_frame_type),
        method(focus_frame, is_keyboard_enabled),
        method(focus_frame, is_mouse_enabled),
        method(focus_frame, is_mouse_wheel_enabled),
        method(focus_frame, is_movable),
        method(focus_frame, is_resizable),
        method(focus_frame, is_top_level),
        method(focus_frame, is_user_placed),
        method(focus_frame, on),
        method(focus_frame, raise),
        method(focus_frame, register_all_events),
        method(focus_frame, register_event),
        method(focus_frame, register_for_drag),
        method(focus_frame, set_backdrop),
        method(focus_frame, set_backdrop_border_color),
        method(focus_frame, set_backdrop_color),
        method(focus_frame, set_clamped_to_screen),
        method(focus_frame, set_frame_strata),
        method(focus_frame, set_hit_rect_insets),
        method(focus_frame, set_max_resize),
        method(focus_frame, set_min_resize),
        method(focus_frame, set_movable),
        method(focus_frame, set_resizable),
        method(focus_frame, set_scale),
        method(focus_frame, set_script),
        method(focus_frame, set_top_level),
        method(focus_frame, set_user_placed),
        method(focus_frame, start_moving),
        method(focus_frame, start_sizing),
        method(focus_frame, stop_moving_or_sizing),
        method(focus_frame, unregister_all_events),
        method(focus_frame, unregister_event),

        // focus_frame
        method(focus_frame, clear_focus),
        method(focus_frame, is_auto_focus),
        method(focus_frame, set_auto_focus),
        method(focus_frame, set_focus),

        {0,0}
    };

    const char  lua_edit_box::className[] = "EditBox";
    const char* lua_edit_box::classList[] = {"EditBox", 0};
    lua::Lunar<lua_edit_box>::RegType lua_edit_box::methods[] = {
        {"dt", &lua_edit_box::get_data_table},

        // uiobject (inherited)
        method(edit_box, get_alpha),
        method(edit_box, get_name),
        method(edit_box, get_object_type),
        method(edit_box, is_object_type),
        method(edit_box, set_alpha),

        method(edit_box, clear_all_points),
        method(edit_box, get_base),
        method(edit_box, get_bottom),
        method(edit_box, get_center),
        method(edit_box, get_height),
        method(edit_box, get_left),
        method(edit_box, get_num_point),
        method(edit_box, get_parent),
        method(edit_box, get_point),
        method(edit_box, get_right),
        method(edit_box, get_top),
        method(edit_box, get_width),
        method(edit_box, hide),
        method(edit_box, is_shown),
        method(edit_box, is_visible),
        method(edit_box, set_all_points),
        method(edit_box, set_height),
        method(edit_box, set_parent),
        method(edit_box, set_point),
        method(edit_box, set_rel_point),
        method(edit_box, set_width),
        method(edit_box, show),

        // frame (inherited)
        method(edit_box, create_font_string),
        method(edit_box, create_texture),
        method(edit_box, create_title_region),
        method(edit_box, disable_draw_layer),
        method(edit_box, enable_draw_layer),
        method(edit_box, enable_keyboard),
        method(edit_box, enable_mouse),
        method(edit_box, enable_mouse_wheel),
        method(edit_box, get_backdrop),
        method(edit_box, get_backdrop_border_color),
        method(edit_box, get_backdrop_color),
        method(edit_box, get_children),
        method(edit_box, get_effective_alpha),
        method(edit_box, get_effective_scale),
        method(edit_box, get_frame_level),
        method(edit_box, get_frame_strata),
        method(edit_box, get_frame_type),
        method(edit_box, get_hit_rect_insets),
        method(edit_box, get_id),
        method(edit_box, get_max_resize),
        method(edit_box, get_min_resize),
        method(edit_box, set_max_width),
        method(edit_box, set_max_height),
        method(edit_box, set_min_width),
        method(edit_box, set_min_height),
        method(edit_box, get_num_children),
        method(edit_box, get_num_regions),
        method(edit_box, get_scale),
        method(edit_box, get_script),
        method(edit_box, get_title_region),
        method(edit_box, has_script),
        method(edit_box, is_clamped_to_screen),
        method(edit_box, is_frame_type),
        method(edit_box, is_keyboard_enabled),
        method(edit_box, is_mouse_enabled),
        method(edit_box, is_mouse_wheel_enabled),
        method(edit_box, is_movable),
        method(edit_box, is_resizable),
        method(edit_box, is_top_level),
        method(edit_box, is_user_placed),
        method(edit_box, on),
        method(edit_box, raise),
        method(edit_box, register_all_events),
        method(edit_box, register_event),
        method(edit_box, register_for_drag),
        method(edit_box, set_backdrop),
        method(edit_box, set_backdrop_border_color),
        method(edit_box, set_backdrop_color),
        method(edit_box, set_clamped_to_screen),
        method(edit_box, set_frame_strata),
        method(edit_box, set_hit_rect_insets),
        method(edit_box, set_max_resize),
        method(edit_box, set_min_resize),
        method(edit_box, set_movable),
        method(edit_box, set_resizable),
        method(edit_box, set_scale),
        method(edit_box, set_script),
        method(edit_box, set_top_level),
        method(edit_box, set_user_placed),
        method(edit_box, start_moving),
        method(edit_box, start_sizing),
        method(edit_box, stop_moving_or_sizing),
        method(edit_box, unregister_all_events),
        method(edit_box, unregister_event),

        // focus_frame (inherited)
        method(edit_box, clear_focus),
        method(edit_box, is_auto_focus),
        method(edit_box, set_auto_focus),
        method(edit_box, set_focus),

        // edit_box
        method(edit_box, add_history_line),
        method(edit_box, get_blink_speed),
        method(edit_box, get_history_lines),
        method(edit_box, get_max_letters),
        method(edit_box, get_num_letters),
        method(edit_box, get_number),
        method(edit_box, get_text),
        method(edit_box, get_text_insets),
        method(edit_box, highlight_text),
        method(edit_box, insert),
        method(edit_box, is_multi_line),
        method(edit_box, is_numeric),
        method(edit_box, is_password),
        method(edit_box, set_blink_speed),
        method(edit_box, set_max_history_lines),
        method(edit_box, set_max_letters),
        method(edit_box, set_multi_line),
        method(edit_box, set_number),
        method(edit_box, set_numeric),
        method(edit_box, set_password),
        method(edit_box, set_text),
        method(edit_box, set_text_insets),

        {0,0}
    };

    const char  lua_scroll_frame::className[] = "ScrollFrame";
    const char* lua_scroll_frame::classList[] = {"ScrollFrame", 0};
    lua::Lunar<lua_scroll_frame>::RegType lua_scroll_frame::methods[] = {
        {"dt", &lua_scroll_frame::get_data_table},

        // uiobject (inherited)
        method(scroll_frame, get_alpha),
        method(scroll_frame, get_name),
        method(scroll_frame, get_object_type),
        method(scroll_frame, is_object_type),
        method(scroll_frame, set_alpha),

        method(scroll_frame, clear_all_points),
        method(scroll_frame, get_base),
        method(scroll_frame, get_bottom),
        method(scroll_frame, get_center),
        method(scroll_frame, get_height),
        method(scroll_frame, get_left),
        method(scroll_frame, get_num_point),
        method(scroll_frame, get_parent),
        method(scroll_frame, get_point),
        method(scroll_frame, get_right),
        method(scroll_frame, get_top),
        method(scroll_frame, get_width),
        method(scroll_frame, hide),
        method(scroll_frame, is_shown),
        method(scroll_frame, is_visible),
        method(scroll_frame, set_all_points),
        method(scroll_frame, set_height),
        method(scroll_frame, set_parent),
        method(scroll_frame, set_point),
        method(scroll_frame, set_rel_point),
        method(scroll_frame, set_width),
        method(scroll_frame, show),

        // frame (inherited)
        method(scroll_frame, create_font_string),
        method(scroll_frame, create_texture),
        method(scroll_frame, create_title_region),
        method(scroll_frame, disable_draw_layer),
        method(scroll_frame, enable_draw_layer),
        method(scroll_frame, enable_keyboard),
        method(scroll_frame, enable_mouse),
        method(scroll_frame, enable_mouse_wheel),
        method(scroll_frame, get_backdrop),
        method(scroll_frame, get_backdrop_border_color),
        method(scroll_frame, get_backdrop_color),
        method(scroll_frame, get_children),
        method(scroll_frame, get_effective_alpha),
        method(scroll_frame, get_effective_scale),
        method(scroll_frame, get_frame_level),
        method(scroll_frame, get_frame_strata),
        method(scroll_frame, get_frame_type),
        method(scroll_frame, get_hit_rect_insets),
        method(scroll_frame, get_id),
        method(scroll_frame, get_max_resize),
        method(scroll_frame, get_min_resize),
        method(scroll_frame, set_max_width),
        method(scroll_frame, set_max_height),
        method(scroll_frame, set_min_width),
        method(scroll_frame, set_min_height),
        method(scroll_frame, get_num_children),
        method(scroll_frame, get_num_regions),
        method(scroll_frame, get_scale),
        method(scroll_frame, get_script),
        method(scroll_frame, get_title_region),
        method(scroll_frame, has_script),
        method(scroll_frame, is_clamped_to_screen),
        method(scroll_frame, is_frame_type),
        method(scroll_frame, is_keyboard_enabled),
        method(scroll_frame, is_mouse_enabled),
        method(scroll_frame, is_mouse_wheel_enabled),
        method(scroll_frame, is_movable),
        method(scroll_frame, is_resizable),
        method(scroll_frame, is_top_level),
        method(scroll_frame, is_user_placed),
        method(scroll_frame, on),
        method(scroll_frame, raise),
        method(scroll_frame, register_all_events),
        method(scroll_frame, register_event),
        method(scroll_frame, register_for_drag),
        method(scroll_frame, set_backdrop),
        method(scroll_frame, set_backdrop_border_color),
        method(scroll_frame, set_backdrop_color),
        method(scroll_frame, set_clamped_to_screen),
        method(scroll_frame, set_frame_strata),
        method(scroll_frame, set_hit_rect_insets),
        method(scroll_frame, set_max_resize),
        method(scroll_frame, set_min_resize),
        method(scroll_frame, set_movable),
        method(scroll_frame, set_resizable),
        method(scroll_frame, set_scale),
        method(scroll_frame, set_script),
        method(scroll_frame, set_top_level),
        method(scroll_frame, set_user_placed),
        method(scroll_frame, start_moving),
        method(scroll_frame, start_sizing),
        method(scroll_frame, stop_moving_or_sizing),
        method(scroll_frame, unregister_all_events),
        method(scroll_frame, unregister_event),

        // ScrollFrame
        method(scroll_frame, get_horizontal_scroll),
        method(scroll_frame, get_horizontal_scroll_range),
        method(scroll_frame, get_scroll_child),
        method(scroll_frame, get_vertical_scroll),
        method(scroll_frame, get_vertical_scroll_range),
        method(scroll_frame, set_horizontal_scroll),
        method(scroll_frame, set_scroll_child),
        method(scroll_frame, set_vertical_scroll),

        {0,0}
    };

    const char  lua_button::className[] = "Button";
    const char* lua_button::classList[] = {"Button", "CheckButton", 0};
    lua::Lunar<lua_button>::RegType lua_button::methods[] = {
        {"dt", &lua_button::get_data_table},

        // uiobject (inherited)
        method(button, get_alpha),
        method(button, get_name),
        method(button, get_object_type),
        method(button, is_object_type),
        method(button, set_alpha),

        method(button, clear_all_points),
        method(button, get_base),
        method(button, get_bottom),
        method(button, get_center),
        method(button, get_height),
        method(button, get_left),
        method(button, get_num_point),
        method(button, get_parent),
        method(button, get_point),
        method(button, get_right),
        method(button, get_top),
        method(button, get_width),
        method(button, hide),
        method(button, is_shown),
        method(button, is_visible),
        method(button, set_all_points),
        method(button, set_height),
        method(button, set_parent),
        method(button, set_point),
        method(button, set_rel_point),
        method(button, set_width),
        method(button, show),

        // frame (inherited)
        method(button, create_font_string),
        method(button, create_texture),
        method(button, create_title_region),
        method(button, disable_draw_layer),
        method(button, enable_draw_layer),
        method(button, enable_keyboard),
        method(button, enable_mouse),
        method(button, enable_mouse_wheel),
        method(button, get_backdrop),
        method(button, get_backdrop_border_color),
        method(button, get_backdrop_color),
        method(button, get_children),
        method(button, get_effective_alpha),
        method(button, get_effective_scale),
        method(button, get_frame_level),
        method(button, get_frame_strata),
        method(button, get_frame_type),
        method(button, get_hit_rect_insets),
        method(button, get_id),
        method(button, get_max_resize),
        method(button, get_min_resize),
        method(button, set_max_width),
        method(button, set_max_height),
        method(button, set_min_width),
        method(button, set_min_height),
        method(button, get_num_children),
        method(button, get_num_regions),
        method(button, get_scale),
        method(button, get_script),
        method(button, get_title_region),
        method(button, has_script),
        method(button, is_clamped_to_screen),
        method(button, is_frame_type),
        method(button, is_keyboard_enabled),
        method(button, is_mouse_enabled),
        method(button, is_mouse_wheel_enabled),
        method(button, is_movable),
        method(button, is_resizable),
        method(button, is_top_level),
        method(button, is_user_placed),
        method(button, on),
        method(button, raise),
        method(button, register_all_events),
        method(button, register_event),
        method(button, register_for_drag),
        method(button, set_backdrop),
        method(button, set_backdrop_border_color),
        method(button, set_backdrop_color),
        method(button, set_clamped_to_screen),
        method(button, set_frame_strata),
        method(button, set_hit_rect_insets),
        method(button, set_max_resize),
        method(button, set_min_resize),
        method(button, set_movable),
        method(button, set_resizable),
        method(button, set_scale),
        method(button, set_script),
        method(button, set_top_level),
        method(button, set_user_placed),
        method(button, start_moving),
        method(button, start_sizing),
        method(button, stop_moving_or_sizing),
        method(button, unregister_all_events),
        method(button, unregister_event),

        // Button
        method(button, click),
        method(button, disable),
        method(button, enable),
        method(button, get_button_state),
        method(button, get_disabled_font_object),
        method(button, get_disabled_text_color),
        method(button, get_disabled_texture),
        method(button, get_highlight_font_object),
        method(button, get_highlight_text_color),
        method(button, get_highlight_texture),
        method(button, get_normal_font_object),
        method(button, get_normal_texture),
        method(button, get_pushed_text_offset),
        method(button, get_pushed_texture),
        method(button, get_text),
        method(button, get_text_height),
        method(button, get_text_width),
        method(button, is_enabled),
        method(button, lock_highlight),
        method(button, set_button_state),
        method(button, set_disabled_font_object),
        method(button, set_disabled_text_color),
        method(button, set_disabled_texture),
        method(button, set_highlight_font_object),
        method(button, set_highlight_text_color),
        method(button, set_highlight_texture),
        method(button, set_normal_font_object),
        method(button, set_normal_text_color),
        method(button, set_normal_texture),
        method(button, set_pushed_text_offset),
        method(button, set_pushed_texture),
        method(button, set_text),
        method(button, unlock_highlight),

        {0,0}
    };

    const char  lua_slider::className[] = "Slider";
    const char* lua_slider::classList[] = {"Slider", 0};
    lua::Lunar<lua_slider>::RegType lua_slider::methods[] = {
        {"dt", &lua_slider::get_data_table},

        // uiobject (inherited)
        method(slider, get_alpha),
        method(slider, get_name),
        method(slider, get_object_type),
        method(slider, is_object_type),
        method(slider, set_alpha),

        method(slider, clear_all_points),
        method(slider, get_base),
        method(slider, get_bottom),
        method(slider, get_center),
        method(slider, get_height),
        method(slider, get_left),
        method(slider, get_num_point),
        method(slider, get_parent),
        method(slider, get_point),
        method(slider, get_right),
        method(slider, get_top),
        method(slider, get_width),
        method(slider, hide),
        method(slider, is_shown),
        method(slider, is_visible),
        method(slider, set_all_points),
        method(slider, set_height),
        method(slider, set_parent),
        method(slider, set_point),
        method(slider, set_rel_point),
        method(slider, set_width),
        method(slider, show),

        // frame (inherited)
        method(slider, create_font_string),
        method(slider, create_texture),
        method(slider, create_title_region),
        method(slider, disable_draw_layer),
        method(slider, enable_draw_layer),
        method(slider, enable_keyboard),
        method(slider, enable_mouse),
        method(slider, enable_mouse_wheel),
        method(slider, get_backdrop),
        method(slider, get_backdrop_border_color),
        method(slider, get_backdrop_color),
        method(slider, get_children),
        method(slider, get_effective_alpha),
        method(slider, get_effective_scale),
        method(slider, get_frame_level),
        method(slider, get_frame_strata),
        method(slider, get_frame_type),
        method(slider, get_hit_rect_insets),
        method(slider, get_id),
        method(slider, get_max_resize),
        method(slider, get_min_resize),
        method(slider, set_max_width),
        method(slider, set_max_height),
        method(slider, set_min_width),
        method(slider, set_min_height),
        method(slider, get_num_children),
        method(slider, get_num_regions),
        method(slider, get_scale),
        method(slider, get_script),
        method(slider, get_title_region),
        method(slider, has_script),
        method(slider, is_clamped_to_screen),
        method(slider, is_frame_type),
        method(slider, is_keyboard_enabled),
        method(slider, is_mouse_enabled),
        method(slider, is_mouse_wheel_enabled),
        method(slider, is_movable),
        method(slider, is_resizable),
        method(slider, is_top_level),
        method(slider, is_user_placed),
        method(slider, on),
        method(slider, raise),
        method(slider, register_all_events),
        method(slider, register_event),
        method(slider, register_for_drag),
        method(slider, set_backdrop),
        method(slider, set_backdrop_border_color),
        method(slider, set_backdrop_color),
        method(slider, set_clamped_to_screen),
        method(slider, set_frame_strata),
        method(slider, set_hit_rect_insets),
        method(slider, set_max_resize),
        method(slider, set_min_resize),
        method(slider, set_movable),
        method(slider, set_resizable),
        method(slider, set_scale),
        method(slider, set_script),
        method(slider, set_top_level),
        method(slider, set_user_placed),
        method(slider, start_moving),
        method(slider, start_sizing),
        method(slider, stop_moving_or_sizing),
        method(slider, unregister_all_events),
        method(slider, unregister_event),

        // StatusBar
        method(slider, allow_clicks_outside_thumb),
        method(slider, get_max_value),
        method(slider, get_min_value),
        method(slider, get_min_max_values),
        method(slider, get_orientation),
        method(slider, get_thumb_texture),
        method(slider, get_value),
        method(slider, get_value_step),
        method(slider, set_max_value),
        method(slider, set_min_value),
        method(slider, set_min_max_values),
        method(slider, set_orientation),
        method(slider, set_thumb_texture),
        method(slider, set_value),
        method(slider, set_value_step),

        {0,0}
    };

    const char  lua_layered_region::className[] = "LayeredRegion";
    const char* lua_layered_region::classList[] = {"LayeredRegion",
        "Texture", "FontString", 0
    };
    lua::Lunar<lua_layered_region>::RegType lua_layered_region::methods[] = {
        {"dt", &lua_layered_region::get_data_table},
        {0,0}
    };

    const char  lua_texture::className[] = "Texture";
    const char* lua_texture::classList[] = {"Texture", 0};
    lua::Lunar<lua_texture>::RegType lua_texture::methods[] = {
        {"dt", &lua_texture::get_data_table},

        // uiobject (inherited)
        method(texture, get_alpha),
        method(texture, get_name),
        method(texture, get_object_type),
        method(texture, is_object_type),
        method(texture, set_alpha),

        method(texture, clear_all_points),
        method(texture, get_base),
        method(texture, get_bottom),
        method(texture, get_center),
        method(texture, get_height),
        method(texture, get_left),
        method(texture, get_num_point),
        method(texture, get_parent),
        method(texture, get_point),
        method(texture, get_right),
        method(texture, get_top),
        method(texture, get_width),
        method(texture, hide),
        method(texture, is_shown),
        method(texture, is_visible),
        method(texture, set_all_points),
        method(texture, set_height),
        method(texture, set_parent),
        method(texture, set_point),
        method(texture, set_rel_point),
        method(texture, set_width),
        method(texture, show),

        // layered_region (inherited)
        method(texture, get_draw_layer),
        method(texture, set_draw_layer),

        // texture
        method(texture, get_blend_mode),
        method(texture, get_filter_mode),
        method(texture, get_tex_coord),
        method(texture, get_tex_coord_modifies_rect),
        method(texture, get_texture),
        method(texture, get_vertex_color),
        method(texture, is_desaturated),
        method(texture, set_blend_mode),
        method(texture, set_filter_mode),
        method(texture, set_desaturated),
        method(texture, set_gradient),
        method(texture, set_gradient_alpha),
        method(texture, set_tex_coord),
        method(texture, set_tex_coord_modifies_rect),
        method(texture, set_texture),
        method(texture, set_vertex_color),

        {0,0}
    };

    const char  lua_font_string::className[] = "FontString";
    const char* lua_font_string::classList[] = {"FontString", 0};
    lua::Lunar<lua_font_string>::RegType lua_font_string::methods[] = {
        {"dt", &lua_font_string::get_data_table},

        // uiobject (inherited)
        method(font_string, get_alpha),
        method(font_string, get_name),
        method(font_string, get_object_type),
        method(font_string, is_object_type),
        method(font_string, set_alpha),

        method(font_string, clear_all_points),
        method(font_string, get_base),
        method(font_string, get_bottom),
        method(font_string, get_center),
        method(font_string, get_height),
        method(font_string, get_left),
        method(font_string, get_num_point),
        method(font_string, get_parent),
        method(font_string, get_point),
        method(font_string, get_right),
        method(font_string, get_top),
        method(font_string, get_width),
        method(font_string, hide),
        method(font_string, is_shown),
        method(font_string, is_visible),
        method(font_string, set_all_points),
        method(font_string, set_height),
        method(font_string, set_parent),
        method(font_string, set_point),
        method(font_string, set_rel_point),
        method(font_string, set_width),
        method(font_string, show),

        // layered_region (inherited)
        method(font_string, get_draw_layer),
        method(font_string, set_draw_layer),

        // font_string
        method(font_string, get_font),
        method(font_string, get_justify_h),
        method(font_string, get_justify_v),
        method(font_string, get_shadow_color),
        method(font_string, get_shadow_offset),
        method(font_string, get_spacing),
        method(font_string, get_text_color),
        method(font_string, set_font),
        method(font_string, set_justify_h),
        method(font_string, set_justify_v),
        method(font_string, set_shadow_color),
        method(font_string, set_shadow_offset),
        method(font_string, set_spacing),
        method(font_string, set_text_color),
        method(font_string, can_non_space_wrap),
        method(font_string, can_word_wrap),
        method(font_string, enable_formatting),
        method(font_string, get_string_height),
        method(font_string, get_string_width),
        method(font_string, get_text),
        method(font_string, is_formatting_enabled),
        method(font_string, set_non_space_wrap),
        method(font_string, set_text),
        method(font_string, set_word_wrap),

        {0,0}
    };
}
}
